### ISSUE TITLE
Symfony integration

### ISSUE THREAD

**Issue by davidromani** [neemzy/share-extension#8]
Hello.

There is some Symfony Bundle integration? Or could you provide some code example to do it?

Thx.

**Comment by neemzy** [comment]
Hi,

As far as I know, the only thing required to make this extension available in Twig in full-stack Symfony is to register it as a service, as explained [in the Symfony docs](http://symfony.com/doc/current/cookbook/templating/twig_extension.html#register-an-extension-as-a-service).

I honestly am not planning to actually release a bundle just for that, but feel free to do so, I'd gladly put a link to it in this project's README.

Cheers!

**Comment by davidromani** [comment]
@neemzy ok, thanks

**Comment by bryce-gilhome** [comment]
For anyone else needing this (and also to verify this is correct practice :) ): you need a class that returns a SocialShare instance via its constructor.

```
class myInstance extends SocialShare {
  public function __construct() {
    return ShareExtension::getInstance();
  }
}

```
You then need to register that as a Symfony service, and then register the Twig extension using the SocialShare instance service as an argument:

```
  twig.extension.neemzy.share.myInstance:
    class: myNamespace\myInstance

  twig.extension.neemzy.share:
    class: Neemzy\Twig\Extension\Share\ShareExtension
    tags:
      - { name: twig.extension }
    arguments: ['@twig.extension.neemzy.share.myInstance']
```

**Comment by bryce-gilhome** [comment]
Actually this didn't quite work for me - I didn't realise ShareExtension::getInstance() returns an instance of ShareExtension, not SocialShare. The easiest way is to just use that in a factory service like:

```
  twig.extension.neemzy.share:
    class: Neemzy\Twig\Extension\Share\ShareExtension
    factory: ['Neemzy\Twig\Extension\Share\ShareExtension', getInstance]
    tags:
      - { name: twig.extension }
```

(The 'class' key isn't used to create the service with but Symfony wanted it there.)
